config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}

  root    'home#index'

  get     'search',                   to: 'search#search',              as: 'search'
  get     'search-items',             to: 'search#autocomplete',        as: 'search_autocomplete'

  post     'user',                    to: 'fingerprint#lookupUser',     as: 'lookup_user'
  post     'identifier',              to: 'fingerprint#update',         as: 'update_identifier'

  get     'games',                    to: 'games#index',                as: 'games_index'
  get     ':id',                      to: 'games#show',                 as: 'game'
  post    'games/new',                to: 'games#create',               as: 'new_game'
  patch   'games/update/:id',         to: 'games#update',               as: 'edit_game'
  get     'games/approve/:id',        to: 'games#approve',              as: 'approve_game'
  get     'games/reject/:id',         to: 'games#reject',               as: 'reject_game'

  post    'max_ranks/new',            to: 'max_ranks#create',           as: 'new_max_rank'
  get     'max_ranks/verify/:id',     to: 'max_ranks#verify',           as: 'verify_max_rank'
  get     'max_ranks/unverify/:id',   to: 'max_ranks#unverify',         as: 'unverify_max_rank'


  post    'votes/new',                to: 'votes#create',               as: 'new_vote'

end

app/models/max_rank.rb
class MaxRank < ActiveRecord::Base
  belongs_to :game
  belongs_to :rank_type
  belongs_to :user
  has_many :vote

  after_commit :clear_recent_activity
  after_commit :clear_unverified_max_ranks
  after_commit :clear_verified_max_ranks

  validates :source, presence: true
  validates :user, presence: true

  def upvotes
    Vote.where(max_rank_id: id, vote: 1).count
  end

  def downvotes
    Vote.where(max_rank_id: id, vote: -1).count
  end

  def verify
    self.verified = true
    save
  end

  def unverify
    self.verified = false
    save
  end

  def self.sort(array)
    sorted_array = array.sort do |a, b|
      if b[:upvotes] - b[:downvotes] < a[:upvotes] - a[:downvotes]
        -1
      elsif b[:upvotes] - b[:downvotes] > a[:upvotes] - a[:downvotes]
        1
      else
        b[:upvotes] + b[:downvotes] <=> a[:upvotes] + a[:downvotes]
      end
    end
  end

  private
  
  def clear_recent_activity
    Rails.cache.delete('home/recent-activity')
  end

  def clear_unverified_max_ranks
    Rails.cache.delete("max_ranks/unverified/#{self.game.id}-#{self.game.name}")
  end

  def clear_verified_max_ranks
    Rails.cache.delete("max_ranks/verified/#{self.game.id}-#{self.game.name}")
  end
  
end

app/controllers/max_ranks_controller.rb
class MaxRanksController < ApplicationController
  before_action :validate_recaptcha, only: :create
  before_action :set_max_rank, only: [:verify, :unverify]
  before_action :authenticate_admin_user!, only: [:verify, :unverify]
  after_action :clear_user_votes, only: :create

  def create
    params[:max_rank][:user_id] = current_user ? current_user.id : nil
    @max_rank = MaxRank.new(max_rank_params)
    if @max_rank.save
      flash[:success] = "Successfully created #{@max_rank.rank_type.name} for #{@max_rank.game.name}."
      Vote.create(max_rank_id: @max_rank.id, user_id: current_user.id, vote: 1)
    else
      flash[:error] = 'Error creating a max rank.'
    end
    redirect_back
  end

  def verify
    if @max_rank && @max_rank.verify
      flash[:success] = "Successfully verified Max Rank #{@max_rank.id}."
    else
      flash[:error] = "Max Rank #{params[:id]} could not be found."
    end
    redirect_back
  end

  def unverify
    if @max_rank && @max_rank.unverify
      flash[:success] = "Successfully unverified Max Rank #{@max_rank.id}."
    else
      flash[:error] = "Max Rank #{params[:id]} could not be found."
    end
    redirect_back
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def max_rank_params
    params.require(:max_rank).permit(:rank_type_id, :value, :source, :game_id, :user_id)
  end

  def set_max_rank
    @max_rank = MaxRank.find_by_id(params[:id])
  end


  def clear_user_votes
    Rails.cache.delete("votes/#{current_user.id}-#{@max_rank.game.id}") if @max_rank && @max_rank.game && current_user
  end
end

app/views/max_rank/_form.html.erb
<% @max_rank = MaxRank.new %>
<div class="panel panel-default">
  <div class="panel-heading">
    Add Max Rank
  </div>
  <div class="panel-body">
    <%= form_for(@max_rank, url: new_max_rank_path) do |f| %>

      <% if @game %>
        <%= f.hidden_field :game_id, value: @game.id %>
      <% else %>
        <div class="form-group">
          <%= f.select :game_id, Game.select_list, {}, {id: 'game-select2', class: 'select2'} %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.select :rank_type_id, RankType.select_list, {}, {id: 'rank-type-select2', class: 'select2', id: 'rank-type-select2'} %>
      </div>
      <div class="form-group">
        <%= f.text_field :value, placeholder: 'Value', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.text_field :source, placeholder: 'Source', class: 'form-control', type: 'URL' %>
      </div>
      <div class="form-group">
        <div class="g-recaptcha" id="recaptcha-max-rank"></div>
      </div>
      <div class="form-group">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>