config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}

  root    'home#index'

  get     'search',                   to: 'search#search',              as: 'search'
  get     'search-items',             to: 'search#autocomplete',        as: 'search_autocomplete'

  post     'user',                    to: 'fingerprint#lookupUser',     as: 'lookup_user'
  post     'identifier',              to: 'fingerprint#update',         as: 'update_identifier'

  get     'games',                    to: 'games#index',                as: 'games_index'
  get     ':id',                      to: 'games#show',                 as: 'game'
  post    'games/new',                to: 'games#create',               as: 'new_game'
  patch   'games/update/:id',         to: 'games#update',               as: 'edit_game'
  get     'games/approve/:id',        to: 'games#approve',              as: 'approve_game'
  get     'games/reject/:id',         to: 'games#reject',               as: 'reject_game'

  post    'max_ranks/new',            to: 'max_ranks#create',           as: 'new_max_rank'
  get     'max_ranks/verify/:id',     to: 'max_ranks#verify',           as: 'verify_max_rank'
  get     'max_ranks/unverify/:id',   to: 'max_ranks#unverify',         as: 'unverify_max_rank'


  post    'votes/new',                to: 'votes#create',               as: 'new_vote'

end

app/models/game.rb
class Game < ActiveRecord::Base
  extend FriendlyId
  require 'open-uri'
  belongs_to :theme
  has_many :max_rank
  has_many :vote, through: :max_rank

  validates :name, presence: true
  before_create :set_theme
  after_create :fix_slug

  paginates_per 25
  friendly_id :slug_candidates, use: [:slugged, :finders]
  mount_uploader :image, GameImageUploader
  
  def approve
    self.status = 'Approved'
    save
  end
  
  def reject
    self.status = 'Rejected'
    save
  end

  def slug_candidates
    [
      :name,
      [:name, :id]
    ]
  end
  
  def self.getJSON
    game_platforms = [ 'ps4', 'xboxone', 'ps3', 'xbox360', 'pc', 'wii-u' ]
    
    headers =  {'X-Mashape-Key' => ENV['X_MASHAPE_KEY']}
    base_url = 'https://byroredux-metacritic.p.mashape.com/'
    
    games_hash = {}
    game_platforms.each do |platform|
      games_hash["#{platform}"] = JSON.load(open("#{base_url}game-list/#{platform}/new-releases", headers))
    end
    
    games_hash
  end
  
  def self.import
    games_hash = self.getJSON
    games_added = []
    games_hash.each do |platform, games|
      games['results'].each do |game|
        unless Game.where(name: game['name']).first
          games_added << Game.create(name: game['name'])
        end
      end
    end
    games_added
  end
  
  def self.select_list
    approved_games = Game.where(status: "Approved").order(:name)
    select_list_array = approved_games.map do |game|
      [game.name, game.id]
    end
    select_list_array.unshift([-1])
  end
  
  private

  def set_theme
    self.theme_id = Theme.order('RANDOM()').first.id unless theme_id
  end
  
  def fix_slug
    self.slug = nil
    self.save!
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_admin_user!, only: [:approve, :reject, :update]
  before_action :set_game, only: [:show, :update]
  before_action :validate_recaptcha, only: :create
  before_action :check_pending, only: :show
  after_action :clear_recently_added, only: [:approve, :reject]
  after_action :clear_games_all, only: [:approve, :reject]

  def index
    @games = Rails.cache.fetch("games/all-#{params[:page]}", expires_in: 1.day) do
      Kaminari.paginate_array(Game.where(status: 'Approved').order(:name).to_a).page(params[:page]).per(25)
    end
  end

  def show
    @unverified_max_ranks_array = Rails.cache.fetch("max_ranks/unverified/#{@game.id}-#{@game.name}", expires_in: 1.day) do
      unverified_max_ranks = MaxRank.where(game_id: @game.id, verified: false)
      unverified_max_ranks_array = unverified_max_ranks.map do |max_rank|
        rank_info = {
            max_rank: max_rank,
            upvotes: max_rank.upvotes,
            downvotes: max_rank.downvotes
        }
      end
      MaxRank.sort(unverified_max_ranks_array)
    end

    @verified_max_ranks_array = Rails.cache.fetch("max_ranks/verified/#{@game.id}-#{@game.name}", expires_in: 1.day) do
      verified_max_ranks = MaxRank.where(game_id: @game.id, verified: true)
      verified_max_ranks_array = verified_max_ranks.map do |max_rank|
        rank_info = {
            max_rank: max_rank,
            upvotes: max_rank.upvotes,
            downvotes: max_rank.downvotes
        }
      end
      MaxRank.sort(verified_max_ranks_array)
    end
    if current_user
      @votes_hash = Rails.cache.fetch("votes/#{current_user.id}-#{@game.id}", expires_in: 1.day) do
        votes =Vote.joins(:max_rank).where('votes.user_id = ? AND max_ranks.game_id = ?', current_user.id, @game.id)
        votes_hash = {}
        votes.each do |vote|
          votes_hash[vote.max_rank_id] = vote.vote
        end
        votes_hash
      end
    else
      @votes_hash = {}
    end
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:success] = "Successfully created #{@game.name}."
    else
      flash[:error] = 'Error creating a game.'
    end
    redirect_to session[:previous_url] || root_url
  end

  def update
    if @game.update_attributes(game_params)
      flash[:success] = "Successfully updated #{@game.name}."
    else
      flash[:error] = "Error updating #{@game.name}."
    end
    redirect_back
  end

  def approve
    game = Game.find_by_id(params[:id])
    if game
      game.approve
      flash[:success] = "Successfully approved #{game.name}."
    else
      flash[:error] = "Could not find a game with id #{params[:id]}."
    end
    redirect_to admin_approve_games_url
  end

  def reject
    game = Game.find_by_id(params[:id])
    if game
      game.reject
      flash[:success] = "Successfully rejected #{game.name}."
    else
      flash[:error] = "Could not find a game with id #{params[:id]}."
    end
    redirect_to admin_approve_games_url
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:name, :theme_id, :image)
  end

  def check_pending
    if @game.status == 'Pending'
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def clear_recently_added
    Rails.cache.delete('home/recently-added')
  end

  def clear_games_all
    Rails.cache.delete_matched('games/all-*')
  end
end

app/views/games/_admin_menu.html.erb
<% if admin_user_signed_in? %>
  <div class="admin-toggle admin-toggle-closed"><i class="fa fa-bars"></i></div>
  <div class="admin-menu admin-menu-closed">
    <div class="panel panel-default">
      <div class="panel-heading">Admin</div>
      <div class="panel-body">
      <%= form_for(@game, url: edit_game_path(@game.id), multipart: true) do |f| %>
        <div class="form-group">
          <%= f.select :theme_id, {}, {}, {id: 'theme-select2'} do %>
            <% Theme.all.each do |theme| %>
              <% selected = theme.id == @game.theme_id ? true : false %>
              <%= content_tag(:option, theme.name, {selected: selected, value: theme.id, data: {'primary-color' => theme.primary_color, 'secondary-color' => theme.secondary_color }}) %>
            <% end %>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/games/_form.html.erb
<% @game = Game.new %>
<div class="panel panel-default">
  <div class="panel-heading">
    Add Game
  </div>
  <div class="panel-body">
    <%= form_for(@game, url: new_game_path) do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Game Name' %>
    </div>
    <div class="form-group">
      <div class="g-recaptcha" id="recaptcha-game"></div>
    </div>
    <div class="form-group">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
</div>

app/views/games/_max_rank_panel.html.erb
<div class="panel panel-default max-rank-panel rounded">
  <div class="panel-body slim-panel-body">
    <div class="pull-left small-padding">
      <div class="pull-left center-nav-icons">
        <% if max_rank[:max_rank].verified %>
        <i class="fa fa-check bg-success max-rank-icon" data-toggle="tooltip" data-placement="auto" title="" data-original-title="Verified"></i>
        <% elsif max_rank[:upvotes] - max_rank[:downvotes] < 0 %>
        <i class="fa fa-remove bg-danger max-rank-icon" data-toggle="tooltip" data-placement="auto" title="" data-original-title="Unlikely"></i>
        <% else %>
        <i class="fa fa-question bg-primary max-rank-icon" data-toggle="tooltip" data-placement="auto" title="" data-original-title="Not Verified"></i>
        <% end %>
      </div>
      <div class="pull-right display-table">
        <span class="max-rank-text cell"> <%= "#{max_rank[:max_rank].rank_type.name}: #{max_rank[:max_rank].value}" %> </span>
      </div>
    </div>
    <div class="pull-right center-nav-icons">
      <ul id="<%= max_rank[:max_rank].id %>" class="nav-toolbar no-padding">
        <li class="upvote" data-max-rank-id="<%= max_rank[:max_rank].id %>">
          <span class="vote nav-icon<%= ' upvoted' if @votes_hash[max_rank[:max_rank].id] == 1 %>" data-toggle="tooltip" data-placement="auto" title="" data-original-title="<%= max_rank[:upvotes] %>"><i class="fa fa-angle-up"></i></span>
        </li>
        <li class="downvote" data-max-rank-id="<%= max_rank[:max_rank].id %>">
          <span class="vote nav-icon<%= ' downvoted' if @votes_hash[max_rank[:max_rank].id] == -1 %>" data-toggle="tooltip" data-placement="auto" title="" data-original-title="<%= max_rank[:downvotes] %>"><i class="fa fa-angle-down"></i></span>
        </li>
        <li class="dropdown">
          <span class="nav-icon admin" data-toggle="dropdown"><i class="fa fa-ellipsis-v"></i></span>
          <div class="dropdown-menu lg pull-right arrow panel panel-default arrow-top-right">
            <div class="panel-body text-center">
              <div class="row">
                <div class="col-xs-6 col-sm-4 text-yellow" data-toggle="tooltip" data-placement="auto" data-original-title="Submitted By">
                  <span class="h2"><i class="fa fa-user"></i></span>
                  <p class="no-margn">
                    <%= max_rank[:max_rank].user.username %>
                  </p>
                </div>
                <div class="col-xs-6 col-sm-4 text-orange" data-toggle="tooltip" data-placement="auto" data-original-title="<%= max_rank[:max_rank].created_at %>">
                  <span class="h2"><i class="fa fa-clock-o"></i></span>
                  <p class="no-margn">
                    <%= time_ago_in_words(max_rank[:max_rank].created_at) %> ago
                  </p>
                </div>
                <div class="col-xs-12 visible-xs-block">
                  <hr>
                </div>
                <div class="col-xs-6 col-sm-4">
                  <a href="<%= max_rank[:max_rank].source[0..3] == 'http' ? max_rank[:max_rank].source : "http://#{max_rank[:max_rank].source}" %>" class="text-blue" target="_blank"><span class="h2"><i class="fa fa-link"></i></span>
                  <p class="no-margn">
                    Source
                  </p></a>
                </div>
                <% if admin_user_signed_in? %>
                <div class="col-lg-12 col-md-12 col-sm-12 hidden-xs">
                  <hr>
                </div>
                <div class="col-xs-6 col-sm-4">
                  <% if max_rank[:max_rank].verified %>
                  <a href="<%= unverify_max_rank_path(max_rank[:max_rank].id) %>" class="text-green"><span class="h2"> <i class="fa fa-minus-square-o"></i></span>
                  <p class="no-margn">
                    Unverify
                  </p></a>
                  <% else %>
                  <a href="<%= verify_max_rank_path(max_rank[:max_rank].id) %>" class="text-green"><span class="h2"> <i class="fa fa-plus-square-o"></i></span>
                  <p class="no-margn">
                    Verify
                  </p></a>
                  <% end %>
                </div>
                <div class="col-xs-12 visible-xs-block">
                  <hr>
                </div>
                <div class="col-xs-6 col-sm-4">
                  <a href="<%= edit_admin_max_rank_path(max_rank[:max_rank].id) %>" class="text-purple"><span class="h2"><i class="fa fa-edit"></i></span>
                  <p class="no-margn">
                    Edit
                  </p></a>
                </div>
                <div class="col-xs-6 col-sm-4">
                  <a href="<%= admin_max_rank_path(max_rank[:max_rank].id) %>" data-confirm="Are you sure you want to delete this?" rel="nofollow" data-method="delete" class="text-red"><span class="h2"><i class="fa fa-remove"></i></span>
                  <p class="no-margn">
                    Delete
                  </p></a>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<% provide(:title, 'Max ranks for all games') %>
<% provide(:description, 'Find max rank, level cap, points, prestiges, extra levels, and more for all your favorite games.') %>
<% provide(:header, 'Games') %>
<% provide(:small_header, '') %>
<div class="row">
  <div class="col-md-5 col-md-push-7" id="button-col">
    <button id="add-game-button" class="btn btn-success">
      Add Game
    </button>
    <button id="cancel-add-game-button" class="btn btn-danger hidden">
      Cancel
    </button>
  </div>
  <div class="col-md-7 col-md-pull-5">
    <div id="add-game-box" class="hidden">
      <%= render partial: 'form' %>
    </div>
    <div class="list-group">
      <% @games.each do |game| %>
        <%= link_to game.name, game_path(game.slug), class: 'list-group-item' %>
      <% end %>
    </div>
    <%= paginate @games %>
  </div>
</div>

app/views/games/show.html.erb
<% provide(:title, "#{@game.name} Max Ranks") %>
<% provide(:description, "#{@game.name} max rank, level cap, points, prestiges, extra levels, and more.") %>
<% provide(:header, @game.name) %>
<% provide(:small_header, '') %>
<% provide(:game_image, @game.image) %>
<% provide(:theme, @game.theme.name) %>

<div class="row">

  <%= render partial: 'games/admin_menu' %>
  <div class="col-lg-5 col-lg-push-7 col-md-3 col-md-push-9" id="button-col">
    <button id="add-max-rank-button" class="btn btn-success">
      Add Max Rank
    </button>
    <button id="cancel-add-max-rank-button" class="btn btn-danger hidden">
      Cancel
    </button>
  </div>
  <div class="col-lg-7 col-lg-pull-5 col-md-9 col-md-pull-3">
    <div id="add-max-rank-box" class="hidden">
      <%= render partial: 'max_rank/form' %>
    </div>
    <% if @verified_max_ranks_array.count > 0 || @unverified_max_ranks_array.count > 0 %>
      <% @verified_max_ranks_array.each_with_index do |max_rank| %>
        <%= render partial: 'games/max_rank_panel', locals: {max_rank: max_rank} %>
      <% end %>

      <% threshold = nil %>

      <% @unverified_max_ranks_array.each_with_index do |max_rank, i| %>
        <% if max_rank[:upvotes] - max_rank[:downvotes] < 0 || i >= 10
             threshold = i
             break
           end %>
        <%= render partial: 'games/max_rank_panel', locals: {max_rank: max_rank} %>
      <% end %>

      <% if threshold %>
        <button id="threshold-button" class="btn btn-default">
          Show ranks below the threshold
        </button>
        <hr class="clear">
        <div id="threshold">
          <% @unverified_max_ranks_array[threshold, @unverified_max_ranks_array.count - threshold].each_with_index do |max_rank, i| %>
            <%= render partial: 'games/max_rank_panel', locals: {max_rank: max_rank} %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <div role="alert" class="alert alert-warning">
        <h4>There are no max ranks!</h4>

        <p>
          Help us out by submitting a new max rank for this game. You can do that by clicking the green button and
          filling out the form.
        </p>
      </div>
    <% end %>
  </div>
</div>