config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}

  root    'home#index'

  get     'search',                   to: 'search#search',              as: 'search'
  get     'search-items',             to: 'search#autocomplete',        as: 'search_autocomplete'

  post     'user',                    to: 'fingerprint#lookupUser',     as: 'lookup_user'
  post     'identifier',              to: 'fingerprint#update',         as: 'update_identifier'

  get     'games',                    to: 'games#index',                as: 'games_index'
  get     ':id',                      to: 'games#show',                 as: 'game'
  post    'games/new',                to: 'games#create',               as: 'new_game'
  patch   'games/update/:id',         to: 'games#update',               as: 'edit_game'
  get     'games/approve/:id',        to: 'games#approve',              as: 'approve_game'
  get     'games/reject/:id',         to: 'games#reject',               as: 'reject_game'

  post    'max_ranks/new',            to: 'max_ranks#create',           as: 'new_max_rank'
  get     'max_ranks/verify/:id',     to: 'max_ranks#verify',           as: 'verify_max_rank'
  get     'max_ranks/unverify/:id',   to: 'max_ranks#unverify',         as: 'unverify_max_rank'


  post    'votes/new',                to: 'votes#create',               as: 'new_vote'

end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "alert alert-#{key}" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="container-fluid footer">
  Copyright &copy; 2015 <a href="<%= root_url %>">GrindBucket.com</a>
  <a href="#" class="scrollup"><i class="fa fa-chevron-up"></i></a>
</footer>

app/views/layouts/_header.html.erb
<header class="top-head container-fluid header-table">

  <button type="button" class="navbar-toggle cell">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

    <span class="brand cell">
      Grind Bucket
    </span>

  <span id="filler"></span>

  <span class="cell">
    <span class="cell full-width">
      <%= form_tag(search_path, method: "get", class: 'app-search', id: 'search-form') do %>

        <%= text_field_tag :query, params[:query], placeholder: 'e.g. Battlefield Hardline', class: 'form-control form-control-circle', id: 'search-box' %>

      <% end %>
    </span>

      <span id="search-toggle" class="cell"><span class="fa fa-search"></span></span>
  </span>

</header>
<!-- Header Ends -->

app/views/layouts/_left_panel.html.erb
<aside class="left-panel<%= ' collapsed' if cookies[:collapsed] == 'true' %>">

  <% color = current_user ? current_user.color : '#000' %>
  <div class="user text-center no-overflow">
    <div class="img circle-border">
      <div style="background: <%= color %>; border: 2px solid <%= color %>" class="circle-border no-overflow" id="user-color-icon">
        <%= image_tag 'user.png', style: 'width: 48px' %>
      </div>
    </div>
    <h4 class="user-name" data-user="<%= !!current_user %>"><%= current_user.username if current_user %></h4>
  </div>

  <nav class="navigation">
    <ul class="list-unstyled">
      <li>
        <a href="<%= root_path %>"><i class="fa fa-home"></i><span class="nav-label">Home</span></a>
      </li>
      <li>
        <a href="<%= games_index_path %>"><i class="fa fa-gamepad"></i><span class="nav-label">Games</span></a>
      </li>
      <% if defined?(Devise) %>
      <% if admin_user_signed_in? %>
      <li>
        <a href="<%= admin_dashboard_path %>"><i class="fa fa-gear"></i><span class="nav-label">Admin</span></a>
      </li>
      <% end %>
      <% end %>
    </ul>
  </nav>

</aside>

app/views/layouts/_search.html.erb
<%= form_tag(search_path, method: "get", class: 'form-horizontal', id: "search-form") do %>
<div class="input-group">
  <%= text_field_tag :query, params[:query], placeholder: "e.g. Grand Theft Auto", class: "form-control", id: 'search-box' %>
  <span class="input-group-btn"> <%= submit_tag "Search", class: "btn btn-primary" %> </span>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title).empty? ? 'Grind Bucket' : yield(:title)%></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script async src='https://www.google.com/recaptcha/api.js?render=explicit'></script>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<%= yield(:description) %>">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="<%= yield(:theme).empty? ? 'default' : yield(:theme)%>">
    <%= render partial: 'layouts/left_panel' %>
    <section class="content">
      <%= render partial: 'layouts/header' %>
      <div class="game-header <%= yield(:game_image).empty? ? 'default-image' : 'game-image' %>"
      <% if yield(:game_image).present? %>
      style="background-image: url('<%= yield(:game_image) %>')"
      <% end %>
      >
        <h1><span><%= yield(:header) %> <small><%= yield(:small_header) %></small></span></h1>
      </div>
      <div class="warper container-fluid">
        <%= render partial: 'layouts/flash' %>
        <%= yield %>
      </div>
      <%= render partial: 'layouts/footer' %>
    </section>
    <% if Rails.env.production? && !admin_user_signed_in? %>
    <script>
      (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] ||
        function() {
          (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
      })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
      ga('create', 'UA-50909901-4', 'auto');
      ga('send', 'pageview');
    </script>
    <% end %>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!--Info -->
    <title><%= "Error :: #{@app_name}" %></title>

    <!--Styling -->
    <style>
      
		html {
			height: 100%;
			background: #fff asset_url("custom_error_pages/bg.png") bottom repeat-x;
		}
		
		body {
			font-family: Helvetica, Arial, Sans-Serif;
			font-size: 14px;
		}
		.error_container {
			display: block;
			margin: auto;
			margin: 10% auto 0 auto;
			width: 30%;
		}
		
		.error_container .error {
			display: block;
			text-align: center;
		}
		
		.error_container .error img.alert {
			display: block;
			margin: 0 auto 25px auto;
		}
		
		.error_container .message > * {
			display: block;
		}
		
		.error_container .message strong {
			font-weight: bold;
			font-size: 1.5em;
			color: #f00;
			margin: 15px 0 0;
		}

		.error_container .message span {
			margin: 5px auto 0;
			font-size: 0.75em;
			color: #606060;
		}
		
		.error_container .contact {
			display: block;
			text-align: center;
			margin: 20px 0 0 0;
		}
		
		.error_container .contact a {
			display: inline-block;
			margin: 0 -1px; /* For inline block & ERB - HAML removes whitespace; ERB does now - http://haml.info/docs/yardoc/file.REFERENCE.html#whitespace_removal__and_ */
			opacity: 0.4;
			transition: opacity 0.15s ease;
		}

		.error_container .contact a img {
			display: block;
			width: 38px;
			height: 38px;
		}
		
		.error_container .contact a:hover {
			opacity: 0.8;
		}

    </style>
  </head>
  
  <!--Body -->
  <body>
    <div class="error_container">
      <%= yield %>
    </div>
  </body>

</html>